{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "ec08a441-3720-4414-a0b5-73b9044aa162",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-06-18 05:24:51.165 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-18 05:24:51.174 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-18 05:24:57.074 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\MD ZAHEER ULLAH\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-06-18 05:24:57.083 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-18 05:24:57.086 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-18 05:24:57.090 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-18 05:24:57.092 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-18 05:24:57.095 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-18 05:25:07.598 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-18 05:25:07.599 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-18 05:25:07.603 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-18 05:25:07.615 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-18 05:25:07.620 Session state does not function when running a script without `streamlit run`\n",
      "2026-06-18 05:25:07.635 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-18 05:25:07.645 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-18 05:25:07.653 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-18 05:25:07.667 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-18 05:25:07.675 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-18 05:25:07.681 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-18 05:25:08.160 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-18 05:25:08.163 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-18 05:25:08.163 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-18 05:25:08.167 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-18 05:25:08.168 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-18 05:25:08.168 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-18 05:25:08.171 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-18 05:25:08.176 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-18 05:25:08.182 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "#Streamlit text generation \n",
    "import warnings\n",
    "import streamlit as st\n",
    "from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline\n",
    "\n",
    "warnings.filterwarnings(\"ignore\")  # Hide warnings\n",
    "\n",
    "# Page config\n",
    "st.set_page_config(page_title=\"AI Text Generator\", layout=\"centered\")\n",
    "\n",
    "st.title(\"💬 Text Generator\")\n",
    "st.write(\"Select a prompt and generate AI text\")\n",
    "\n",
    "# Model setup\n",
    "model_id = \"distilgpt2\"\n",
    "\n",
    "tok = AutoTokenizer.from_pretrained(model_id)\n",
    "if tok.pad_token is None:\n",
    "    tok.pad_token = tok.eos_token\n",
    "\n",
    "model = AutoModelForCausalLM.from_pretrained(model_id)\n",
    "\n",
    "generator = pipeline(\n",
    "    \"text-generation\",\n",
    "    model=model,\n",
    "    tokenizer=tok,\n",
    ")\n",
    "\n",
    "# 5 Predefined Prompts\n",
    "prompts = [\n",
    "    \"In the future, education will\",\n",
    "    \"Artificial intelligence will change\",\n",
    "    \"Technology in 2030 will\",\n",
    "    \"The role of teachers will\",\n",
    "    \"Online learning will become\",\n",
    "]\n",
    "\n",
    "# User selection dropdown\n",
    "selected_prompt = st.selectbox(\"Choose a prompt:\", prompts)\n",
    "\n",
    "st.write(\"Selected Prompt:\")\n",
    "st.info(selected_prompt)\n",
    "\n",
    "# Generate button and logic\n",
    "if st.button(\"Generate Text\"):\n",
    "    output = generator(\n",
    "        selected_prompt,\n",
    "        max_length=60,\n",
    "        truncation=True,\n",
    "        do_sample=True,\n",
    "        temperature=0.7,\n",
    "        top_p=0.95,\n",
    "        num_return_sequences=1,\n",
    "        pad_token_id=tok.pad_token_id,\n",
    "    )\n",
    "    \n",
    "    st.subheader(\"Generated Text:\")\n",
    "    st.success(output[0][\"generated_text\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "986eb209-dc23-4c3f-8646-ac0f755fa2ed",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
